//
// Generated file, do not edit! Created by nedtool 5.5 from MultiplePackets.msg.
//

#ifndef __MULTIPLEPACKETS_M_H
#define __MULTIPLEPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>MultiplePackets.msg:1</tt> by nedtool.
 * <pre>
 * packet MultiplePackets
 * {
 *     int packetsToSend;
 *     int id;
 * }
 * </pre>
 */
class MultiplePackets : public ::omnetpp::cPacket
{
  protected:
    int packetsToSend;
    int id;

  private:
    void copy(const MultiplePackets& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MultiplePackets&);

  public:
    MultiplePackets(const char *name=nullptr, short kind=0);
    MultiplePackets(const MultiplePackets& other);
    virtual ~MultiplePackets();
    MultiplePackets& operator=(const MultiplePackets& other);
    virtual MultiplePackets *dup() const override {return new MultiplePackets(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketsToSend() const;
    virtual void setPacketsToSend(int packetsToSend);
    virtual int getId() const;
    virtual void setId(int id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MultiplePackets& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MultiplePackets& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MULTIPLEPACKETS_M_H

